### ISSUE TITLE
Make auth more flexible and not require oauth

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub-cloud#207]
Make the default authorization for QHub Bcrypt. This will remove the requirement for DNS and make testing easier (could go to IP of cluster and login instead of waiting for DNS registration) as well get us one step closer to on-prem cluster deployment.

* Make auth more flexible and not require oauth. 
    * OAuth requires https which requires DNS. 
        * So if we use oauth -> we have to have https. 
        * This prevents an on prem deployment along with making testing harder and slower.
    * Make auth more flexible:
        * username/password based auth

Suggested modification to `qhub-config.yaml`

```
security:
  authentication:
    type: password
  users:
    "chris.ostrouchov@gmail.com":
      uid: 1000
      primary_group: users
      password: "salted password with bcrypt base64?" "$5:thesalt:encryptedpassword"
    "dharhas@quansight.com":
      uid: 1001
      primary_group: admin
      password: "salted password with bcrypt base64?"
  groups:
    users:
      gid: 1000
    admin:
      gid: 1001
````
