### ISSUE TITLE
Fix local deployment load balancer

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub-cloud#361]
From @Adam-D-Lewis and @viniciusdc confifuration

```yaml
...
"NetworkID": "14ebd4aca89a154a468a454f3f56812db8e9f999c37c74e086e1bae15e691507",
                    "EndpointID": "47d151b61fb6763dcf6c429ef484eac5f01403a9da01f61c57635568d6ce24e5",
                    "Gateway": "192.168.49.1",
                    "IPAddress": "192.168.49.2",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:c0:a8:31:02",
                    "DriverOpts": null
...
```

For myself

```yaml
...
                    "Aliases": null,
                    "NetworkID": "ef398e8b550789c294b793684d2b7b5335408bab960cca423bab4e859f5b7f61",
                    "EndpointID": "6f8887322b05913b0328a0c59daaa83c0b5ee9abf4197958a9545ee14aac3341",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.3",
                    "IPPrefixLen": 16,
...
```

Correct docs on how to set the load balancer correctly. This will also fix the issue with github actions and not being able to curl the endpoint.
