### ISSUE TITLE
QHub shared filesystem symlink not being initilalized

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub-cloud#370]

**Comment by costrouc** [comment]
Example from @viniciusdc to reproduce

```yaml
sers:
    example-user:
      uid: 1000
      primary_group: users
      secondary_groups:
      - admin
      password: $2b$12$UQHrpBPgRxb/8ZLEitmAcOTjV9Ji/rTQRkeCrEQ4dmedEtzfKU23G
    example-user1:
      uid: 1000
      primary_group: users
      secondary_groups:
      - admin
      password: $2b$12$UQHrpBPgRxb/8ZLEitmAcOTjV9Ji/rTQRkeCrEQ4dmedEtzfKU23G
  groups:
    users:
      gid: 100
    admin:
      gid: 101
```

and the respective home directories were empty (both of them, I've tried creating a share folder but it didn't work)
8:08
I'm using the k9s local deployment
8:10
is it possible that the admin group presented in both created such issue?
8:11
I think I know what happened, maybe the fact I didn't change the user ids was the problem
